package:
  name: recycle
  version: 0.0

# Only use fn and url for polyphemus compatability
source:
  fn: recycle-src.tar.gz # ["TRAVIS" not in environ] 
  url: https://github.com/cyclus/recycle/archive/develop.tar.gz # ["TRAVIS" not in environ]
  path: ..  # ["TRAVIS" in environ]

requirements:
   build:
    - cyclus
    - cmake
    - python
   run:
    - cyclus

test:
  requires:
    - nose
    - pytables

build:
  string: nightly

about:
  home: Cyclus
  license: BSD 3 Clause
